"""Initial migration

Revision ID: 88a6cc242582
Revises: 
Create Date: 2026-02-15 15:11:56.508822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a6cc242582'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('SPEAKING', 'VOCABULARY', 'WRITING', 'STREAK', 'COMPLETION', name='achievementcategory'), nullable=False),
    sa.Column('criteria_type', sa.Enum('DAY_COMPLETE', 'SCORE_THRESHOLD', 'STREAK', 'PLAN_COMPLETE', name='criteriatype'), nullable=False),
    sa.Column('criteria_value', sa.JSON(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='rarity'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('speaking_exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('example_response', sa.Text(), nullable=True),
    sa.Column('focus_areas', sa.JSON(), nullable=False),
    sa.Column('learning_resources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_number', 'cycle_number', name='uq_speaking_day_cycle')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('english_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='englishlevel'), nullable=False),
    sa.Column('primary_goal', sa.Enum('FLUENCY', 'EXAM', 'BUSINESS', 'TRAVEL', name='primarygoal'), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('total_practice_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('vocabulary_words',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('part_of_speech', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PRONOUN', 'PREPOSITION', 'CONJUNCTION', 'INTERJECTION', name='partofspeech'), nullable=False),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('pronunciation_ipa', sa.String(), nullable=False),
    sa.Column('pronunciation_audio_url', sa.String(), nullable=True),
    sa.Column('example_sentences', sa.JSON(), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('antonyms', sa.JSON(), nullable=False),
    sa.Column('usage_tips', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_words_word'), 'vocabulary_words', ['word'], unique=True)
    op.create_table('writing_prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('prompt_title', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('prompt_type', sa.Enum('ESSAY', 'EMAIL', 'STORY', 'OPINION', 'DESCRIPTION', name='prompttype'), nullable=False),
    sa.Column('target_word_count', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('focus_areas', sa.JSON(), nullable=False),
    sa.Column('writing_tips', sa.JSON(), nullable=False),
    sa.Column('sample_outline', sa.Text(), nullable=True),
    sa.Column('learning_resources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_number', 'cycle_number', name='uq_writing_day_cycle')
    )
    op.create_table('analytics_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_category', sa.String(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_name_created', 'analytics_events', ['event_name', 'created_at'], unique=False)
    op.create_index('idx_user_created', 'analytics_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_name'), 'analytics_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('cycle_completions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('speaking_completed', sa.Boolean(), nullable=False),
    sa.Column('vocabulary_completed', sa.Boolean(), nullable=False),
    sa.Column('writing_completed', sa.Boolean(), nullable=False),
    sa.Column('speaking_avg_score', sa.Float(), nullable=True),
    sa.Column('vocabulary_avg_score', sa.Float(), nullable=True),
    sa.Column('writing_avg_score', sa.Float(), nullable=True),
    sa.Column('overall_avg_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cycle_number', name='uq_user_cycle')
    )
    op.create_index(op.f('ix_cycle_completions_user_id'), 'cycle_completions', ['user_id'], unique=False)
    op.create_table('daily_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('speaking_completed', sa.Boolean(), nullable=False),
    sa.Column('vocabulary_completed', sa.Boolean(), nullable=False),
    sa.Column('writing_completed', sa.Boolean(), nullable=False),
    sa.Column('total_minutes_practiced', sa.Integer(), nullable=False),
    sa.Column('words_learned_count', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('exercises_completed_count', sa.Integer(), nullable=False),
    sa.Column('streak_maintained', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_index(op.f('ix_daily_progress_date'), 'daily_progress', ['date'], unique=False)
    op.create_index(op.f('ix_daily_progress_user_id'), 'daily_progress', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('achievement_id', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_type', sa.Enum('SPEAKING', 'VOCABULARY', 'WRITING', name='plantype'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='planstatus'), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('cycles_completed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_type', 'cycle_number', name='uq_user_plan_cycle')
    )
    op.create_index(op.f('ix_user_plans_user_id'), 'user_plans', ['user_id'], unique=False)
    op.create_table('user_vocabulary',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('word_id', sa.String(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'LEARNING', 'REVIEWING', 'MASTERED', name='vocabularystatus'), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('times_reviewed', sa.Integer(), nullable=False),
    sa.Column('times_practiced', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('learned_at', sa.DateTime(), nullable=False),
    sa.Column('mastered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary_words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word')
    )
    op.create_index(op.f('ix_user_vocabulary_user_id'), 'user_vocabulary', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_vocabulary_word_id'), 'user_vocabulary', ['word_id'], unique=False)
    op.create_table('daily_activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_plan_id', sa.String(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('SPEAKING', 'VOCABULARY', 'WRITING', name='plantype'), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'AVAILABLE', 'COMPLETED', name='activitystatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_plan_id'], ['user_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_plan_id', 'day_number', name='uq_plan_day')
    )
    op.create_index(op.f('ix_daily_activities_user_plan_id'), 'daily_activities', ['user_plan_id'], unique=False)
    op.create_table('speaking_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('daily_activity_id', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('words_per_minute', sa.Float(), nullable=False),
    sa.Column('fluency_score', sa.Float(), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=False),
    sa.Column('vocabulary_score', sa.Float(), nullable=False),
    sa.Column('pronunciation_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('pause_count', sa.Integer(), nullable=False),
    sa.Column('filler_words_count', sa.Integer(), nullable=False),
    sa.Column('filler_words_list', sa.JSON(), nullable=False),
    sa.Column('ai_feedback', sa.JSON(), nullable=False),
    sa.Column('grammar_corrections', sa.JSON(), nullable=False),
    sa.Column('vocabulary_suggestions', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_activity_id'], ['daily_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['speaking_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaking_submissions_daily_activity_id'), 'speaking_submissions', ['daily_activity_id'], unique=False)
    op.create_index(op.f('ix_speaking_submissions_exercise_id'), 'speaking_submissions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_speaking_submissions_user_id'), 'speaking_submissions', ['user_id'], unique=False)
    op.create_table('vocabulary_practice_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_vocabulary_id', sa.String(), nullable=False),
    sa.Column('daily_activity_id', sa.String(), nullable=False),
    sa.Column('exercise_type', sa.Enum('FILL_BLANK', 'MATCHING', 'USAGE', 'PRONUNCIATION', name='exercisetype'), nullable=False),
    sa.Column('is_correct', sa.String(), nullable=False),
    sa.Column('user_answer', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('practiced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_activity_id'], ['daily_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_vocabulary_id'], ['user_vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_practice_sessions_daily_activity_id'), 'vocabulary_practice_sessions', ['daily_activity_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_practice_sessions_user_vocabulary_id'), 'vocabulary_practice_sessions', ['user_vocabulary_id'], unique=False)
    op.create_table('writing_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('daily_activity_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=False),
    sa.Column('structure_score', sa.Float(), nullable=False),
    sa.Column('vocabulary_score', sa.Float(), nullable=False),
    sa.Column('coherence_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('grammar_errors', sa.JSON(), nullable=False),
    sa.Column('vocabulary_suggestions', sa.JSON(), nullable=False),
    sa.Column('structure_feedback', sa.Text(), nullable=False),
    sa.Column('ai_feedback', sa.JSON(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_activity_id'], ['daily_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['writing_prompts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_submissions_daily_activity_id'), 'writing_submissions', ['daily_activity_id'], unique=False)
    op.create_index(op.f('ix_writing_submissions_prompt_id'), 'writing_submissions', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_writing_submissions_user_id'), 'writing_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writing_submissions_user_id'), table_name='writing_submissions')
    op.drop_index(op.f('ix_writing_submissions_prompt_id'), table_name='writing_submissions')
    op.drop_index(op.f('ix_writing_submissions_daily_activity_id'), table_name='writing_submissions')
    op.drop_table('writing_submissions')
    op.drop_index(op.f('ix_vocabulary_practice_sessions_user_vocabulary_id'), table_name='vocabulary_practice_sessions')
    op.drop_index(op.f('ix_vocabulary_practice_sessions_daily_activity_id'), table_name='vocabulary_practice_sessions')
    op.drop_table('vocabulary_practice_sessions')
    op.drop_index(op.f('ix_speaking_submissions_user_id'), table_name='speaking_submissions')
    op.drop_index(op.f('ix_speaking_submissions_exercise_id'), table_name='speaking_submissions')
    op.drop_index(op.f('ix_speaking_submissions_daily_activity_id'), table_name='speaking_submissions')
    op.drop_table('speaking_submissions')
    op.drop_index(op.f('ix_daily_activities_user_plan_id'), table_name='daily_activities')
    op.drop_table('daily_activities')
    op.drop_index(op.f('ix_user_vocabulary_word_id'), table_name='user_vocabulary')
    op.drop_index(op.f('ix_user_vocabulary_user_id'), table_name='user_vocabulary')
    op.drop_table('user_vocabulary')
    op.drop_index(op.f('ix_user_plans_user_id'), table_name='user_plans')
    op.drop_table('user_plans')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_daily_progress_user_id'), table_name='daily_progress')
    op.drop_index(op.f('ix_daily_progress_date'), table_name='daily_progress')
    op.drop_table('daily_progress')
    op.drop_index(op.f('ix_cycle_completions_user_id'), table_name='cycle_completions')
    op.drop_table('cycle_completions')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_name'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_index('idx_user_created', table_name='analytics_events')
    op.drop_index('idx_event_name_created', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_table('writing_prompts')
    op.drop_index(op.f('ix_vocabulary_words_word'), table_name='vocabulary_words')
    op.drop_table('vocabulary_words')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('speaking_exercises')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('achievements')
    # ### end Alembic commands ###
