"""r0_initial

Revision ID: 3ecde4d055cc
Revises: 
Create Date: 2026-04-21 10:03:35.852041

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3ecde4d055cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('requirement_type', sa.String(length=50), nullable=True),
    sa.Column('requirement_value', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_achievements_category', 'achievements', ['category'], unique=False)
    op.create_index(op.f('ix_achievements_key'), 'achievements', ['key'], unique=True)
    op.create_table('speaking_exercises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('tips', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_speaking_exercises_cycle_day', 'speaking_exercises', ['cycle', 'day'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('english_level', sa.String(length=10), nullable=True),
    sa.Column('learning_goal', sa.String(length=50), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=64), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    op.create_table('writing_prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('min_words', sa.Integer(), nullable=True),
    sa.Column('max_words', sa.Integer(), nullable=True),
    sa.Column('grammar_focus', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('tips', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_writing_prompts_cycle_day', 'writing_prompts', ['cycle', 'day'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_type', sa.Enum('text', 'voice', name='session_type'), nullable=True),
    sa.Column('scenario_key', sa.String(length=100), nullable=False),
    sa.Column('scenario_title', sa.String(length=200), nullable=False),
    sa.Column('user_level', sa.String(length=10), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=True),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('session_audio_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='session_status'), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('fluency_rating', sa.String(length=50), nullable=True),
    sa.Column('confidence_rating', sa.String(length=50), nullable=True),
    sa.Column('errors_noticed', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('focus_for_next_time', sa.Text(), nullable=True),
    sa.Column('encouragement', sa.Text(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_sessions_user_status', 'conversation_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_status'), 'conversation_sessions', ['status'], unique=False)
    op.create_table('cycle_completions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_xp_earned', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('days_taken', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cycle_completions_user', 'cycle_completions', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index('ix_refresh_tokens_family_id', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('speaking_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=False),
    sa.Column('audio_mime_type', sa.String(length=50), nullable=True),
    sa.Column('audio_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('exercise_prompt_text', sa.Text(), nullable=True),
    sa.Column('user_level', sa.String(length=10), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('fluency_score', sa.Integer(), nullable=True),
    sa.Column('pronunciation_score', sa.Integer(), nullable=True),
    sa.Column('pace_score', sa.Integer(), nullable=True),
    sa.Column('words_mispronounced', sa.JSON(), nullable=True),
    sa.Column('pronunciation_issues', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('improvement_tips', sa.JSON(), nullable=True),
    sa.Column('encouragement', sa.Text(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('analysed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['speaking_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_speaking_submissions_user', 'speaking_submissions', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('achievement_id', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_table('user_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='plan_status'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_plans_user_status', 'user_plans', ['user_id', 'status'], unique=False)
    op.create_table('vocabulary_words',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('position_in_day', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('phonetic', sa.String(length=100), nullable=True),
    sa.Column('part_of_speech', sa.String(length=20), nullable=True),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('example_sentences', sa.JSON(), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('antonyms', sa.JSON(), nullable=True),
    sa.Column('collocations', sa.JSON(), nullable=True),
    sa.Column('memory_tip', sa.Text(), nullable=True),
    sa.Column('register', sa.String(length=20), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vocabulary_words_user_cycle_day', 'vocabulary_words', ['user_id', 'cycle', 'day'], unique=False)
    op.create_index(op.f('ix_vocabulary_words_word'), 'vocabulary_words', ['word'], unique=False)
    op.create_table('writing_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('grammar_score', sa.Integer(), nullable=True),
    sa.Column('vocabulary_score', sa.Integer(), nullable=True),
    sa.Column('coherence_score', sa.Integer(), nullable=True),
    sa.Column('grammar_errors', sa.JSON(), nullable=True),
    sa.Column('vocabulary_suggestions', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('improvement_tips', sa.JSON(), nullable=True),
    sa.Column('encouragement', sa.Text(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('is_revised', sa.Boolean(), nullable=True),
    sa.Column('revision_of', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('analysed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['writing_prompts.id'], ),
    sa.ForeignKeyConstraint(['revision_of'], ['writing_submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_writing_submissions_user', 'writing_submissions', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'ai', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('audio_clip_url', sa.String(length=500), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_messages_session_turn', 'conversation_messages', ['session_id', 'turn_number'], unique=False)
    op.create_table('daily_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('activities_completed', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('speaking_done', sa.Boolean(), nullable=True),
    sa.Column('vocabulary_done', sa.Boolean(), nullable=True),
    sa.Column('writing_done', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['user_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_progress_user_date', 'daily_progress', ['user_id', 'date'], unique=False)
    op.create_table('speaking_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='job_status'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['speaking_submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_speaking_jobs_user_status', 'speaking_jobs', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_speaking_jobs_status'), 'speaking_jobs', ['status'], unique=False)
    op.create_table('vocabulary_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('word_id', sa.String(), nullable=False),
    sa.Column('times_practiced', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('mastery_level', sa.Integer(), nullable=True),
    sa.Column('last_practiced', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary_words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word_progress')
    )
    op.create_index('idx_vocabulary_progress_user_word', 'vocabulary_progress', ['user_id', 'word_id'], unique=False)
    op.create_table('vocabulary_srs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('word_id', sa.String(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('mastery_level', sa.Integer(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('last_reviewed', sa.Date(), nullable=True),
    sa.Column('is_mastered', sa.Boolean(), nullable=True),
    sa.Column('mastered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary_words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word_srs')
    )
    op.create_index('idx_srs_user_mastered', 'vocabulary_srs', ['user_id', 'is_mastered'], unique=False)
    op.create_index('idx_srs_user_review_date', 'vocabulary_srs', ['user_id', 'next_review_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_srs_user_review_date', table_name='vocabulary_srs')
    op.drop_index('idx_srs_user_mastered', table_name='vocabulary_srs')
    op.drop_table('vocabulary_srs')
    op.drop_index('idx_vocabulary_progress_user_word', table_name='vocabulary_progress')
    op.drop_table('vocabulary_progress')
    op.drop_index(op.f('ix_speaking_jobs_status'), table_name='speaking_jobs')
    op.drop_index('idx_speaking_jobs_user_status', table_name='speaking_jobs')
    op.drop_table('speaking_jobs')
    op.drop_index('idx_daily_progress_user_date', table_name='daily_progress')
    op.drop_table('daily_progress')
    op.drop_index('idx_conv_messages_session_turn', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('idx_writing_submissions_user', table_name='writing_submissions')
    op.drop_table('writing_submissions')
    op.drop_index(op.f('ix_vocabulary_words_word'), table_name='vocabulary_words')
    op.drop_index('idx_vocabulary_words_user_cycle_day', table_name='vocabulary_words')
    op.drop_table('vocabulary_words')
    op.drop_index('idx_user_plans_user_status', table_name='user_plans')
    op.drop_table('user_plans')
    op.drop_table('user_achievements')
    op.drop_index('idx_speaking_submissions_user', table_name='speaking_submissions')
    op.drop_table('speaking_submissions')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_cycle_completions_user', table_name='cycle_completions')
    op.drop_table('cycle_completions')
    op.drop_index(op.f('ix_conversation_sessions_status'), table_name='conversation_sessions')
    op.drop_index('idx_conv_sessions_user_status', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index('idx_writing_prompts_cycle_day', table_name='writing_prompts')
    op.drop_table('writing_prompts')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_speaking_exercises_cycle_day', table_name='speaking_exercises')
    op.drop_table('speaking_exercises')
    op.drop_index(op.f('ix_achievements_key'), table_name='achievements')
    op.drop_index('idx_achievements_category', table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
