"""Add daily_commitment to users

Revision ID: 5816217fd41a
Revises: f2d17066fdd5
Create Date: 2026-04-30 15:07:37.475261

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5816217fd41a'
down_revision: Union[str, None] = 'f2d17066fdd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_commitment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_commitment')
    # ### end Alembic commands ###
