"""Add user_id to WritingPrompt

Revision ID: 7b587903f1a9
Revises: 3ecde4d055cc
Create Date: 2026-04-28 22:18:25.160674

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7b587903f1a9'
down_revision: Union[str, None] = '3ecde4d055cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writing_prompts', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index('idx_writing_prompts_user_cycle_day', 'writing_prompts', ['user_id', 'cycle', 'day'], unique=False)
    op.create_foreign_key(None, 'writing_prompts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'writing_prompts', type_='foreignkey')
    op.drop_index('idx_writing_prompts_user_cycle_day', table_name='writing_prompts')
    op.drop_column('writing_prompts', 'user_id')
    # ### end Alembic commands ###
