"""add active_plan_id and current_day to users table

Revision ID: d08491eb54bb
Revises: 5816217fd41a
Create Date: 2026-05-11 22:52:32.512024

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd08491eb54bb'
down_revision: Union[str, None] = '5816217fd41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_plan_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_day', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_active_plan_id'), 'users', ['active_plan_id'], unique=False)
    op.create_foreign_key(None, 'users', 'user_plans', ['active_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_active_plan_id'), table_name='users')
    op.drop_column('users', 'current_day')
    op.drop_column('users', 'active_plan_id')
    # ### end Alembic commands ###
