"""add stripe billing columns

Revision ID: dfde0ea2725e
Revises: a1b2c3d4e5f6
Create Date: 2026-06-29 22:16:20.528988

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dfde0ea2725e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('api_version', sa.String(length=20), nullable=True),
    sa.Column('related_object_id', sa.String(length=64), nullable=True),
    sa.Column('related_object_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('received', 'processed', 'failed', 'ignored', name='webhook_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_events_object', 'stripe_webhook_events', ['related_object_id'], unique=False)
    op.create_index('idx_webhook_events_type_status', 'stripe_webhook_events', ['event_type', 'status'], unique=False)
    op.create_index(op.f('ix_stripe_webhook_events_event_type'), 'stripe_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_stripe_webhook_events_related_object_id'), 'stripe_webhook_events', ['related_object_id'], unique=False)
    op.create_index(op.f('ix_stripe_webhook_events_status'), 'stripe_webhook_events', ['status'], unique=False)
    op.create_table('stripe_checkout_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=128), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=64), nullable=False),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('billing_interval', sa.String(length=10), nullable=False),
    sa.Column('plan_key', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'expired', 'abandoned', name='checkout_session_status_enum'), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checkout_sessions_user_status', 'stripe_checkout_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_stripe_checkout_sessions_status'), 'stripe_checkout_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_stripe_checkout_sessions_stripe_session_id'), 'stripe_checkout_sessions', ['stripe_session_id'], unique=True)
    op.create_index(op.f('ix_stripe_checkout_sessions_user_id'), 'stripe_checkout_sessions', ['user_id'], unique=False)
    op.create_table('stripe_customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=False),
    sa.Column('email_at_creation', sa.String(length=255), nullable=False),
    sa.Column('card_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_stripe_customer_fingerprint', 'stripe_customers', ['card_fingerprint'], unique=False)
    op.create_index('idx_stripe_customer_stripe_id', 'stripe_customers', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_stripe_customers_card_fingerprint'), 'stripe_customers', ['card_fingerprint'], unique=False)
    op.create_index(op.f('ix_stripe_customers_stripe_customer_id'), 'stripe_customers', ['stripe_customer_id'], unique=True)
    op.create_table('stripe_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=64), nullable=False),
    sa.Column('plan_tier', sa.Enum('basic', 'pro', name='plan_tier_enum'), nullable=False),
    sa.Column('billing_interval', sa.Enum('month', 'year', name='billing_interval_enum'), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'canceled', 'unpaid', 'incomplete', 'incomplete_expired', 'paused', name='subscription_status_enum'), nullable=False),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_latest_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_metadata', sa.JSON(), nullable=True),
    sa.Column('pause_collection', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stripe_sub_customer_id', 'stripe_subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index('idx_stripe_sub_stripe_id', 'stripe_subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index('idx_stripe_sub_user_status', 'stripe_subscriptions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_status'), 'stripe_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_stripe_customer_id'), 'stripe_subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_stripe_subscription_id'), 'stripe_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_stripe_subscriptions_user_id'), 'stripe_subscriptions', ['user_id'], unique=False)
    op.create_table('stripe_payment_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=64), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('amount_refunded_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('paid', 'failed', 'refunded', 'partially_refunded', 'void', name='payment_status_enum'), nullable=False),
    sa.Column('payment_type', sa.Enum('subscription', 'trial_conversion', 'one_time', name='payment_type_enum'), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_message', sa.String(length=500), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('invoice_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['stripe_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_records_status', 'stripe_payment_records', ['status'], unique=False)
    op.create_index('idx_payment_records_user_created', 'stripe_payment_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stripe_payment_records_status'), 'stripe_payment_records', ['status'], unique=False)
    op.create_index(op.f('ix_stripe_payment_records_stripe_invoice_id'), 'stripe_payment_records', ['stripe_invoice_id'], unique=True)
    op.create_index(op.f('ix_stripe_payment_records_stripe_payment_intent_id'), 'stripe_payment_records', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_stripe_payment_records_user_id'), 'stripe_payment_records', ['user_id'], unique=False)
    op.alter_column('daily_progress', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('users', sa.Column('stripe_customer_id_cache', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_stripe_customer_id_cache'), 'users', ['stripe_customer_id_cache'], unique=False)
    op.alter_column('vocabulary_srs', 'lapse_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vocabulary_srs', 'lapse_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_users_stripe_customer_id_cache'), table_name='users')
    op.drop_column('users', 'stripe_customer_id_cache')
    op.alter_column('daily_progress', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index(op.f('ix_stripe_payment_records_user_id'), table_name='stripe_payment_records')
    op.drop_index(op.f('ix_stripe_payment_records_stripe_payment_intent_id'), table_name='stripe_payment_records')
    op.drop_index(op.f('ix_stripe_payment_records_stripe_invoice_id'), table_name='stripe_payment_records')
    op.drop_index(op.f('ix_stripe_payment_records_status'), table_name='stripe_payment_records')
    op.drop_index('idx_payment_records_user_created', table_name='stripe_payment_records')
    op.drop_index('idx_payment_records_status', table_name='stripe_payment_records')
    op.drop_table('stripe_payment_records')
    op.drop_index(op.f('ix_stripe_subscriptions_user_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_stripe_subscription_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_stripe_customer_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_status'), table_name='stripe_subscriptions')
    op.drop_index('idx_stripe_sub_user_status', table_name='stripe_subscriptions')
    op.drop_index('idx_stripe_sub_stripe_id', table_name='stripe_subscriptions')
    op.drop_index('idx_stripe_sub_customer_id', table_name='stripe_subscriptions')
    op.drop_table('stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_customers_stripe_customer_id'), table_name='stripe_customers')
    op.drop_index(op.f('ix_stripe_customers_card_fingerprint'), table_name='stripe_customers')
    op.drop_index('idx_stripe_customer_stripe_id', table_name='stripe_customers')
    op.drop_index('idx_stripe_customer_fingerprint', table_name='stripe_customers')
    op.drop_table('stripe_customers')
    op.drop_index(op.f('ix_stripe_checkout_sessions_user_id'), table_name='stripe_checkout_sessions')
    op.drop_index(op.f('ix_stripe_checkout_sessions_stripe_session_id'), table_name='stripe_checkout_sessions')
    op.drop_index(op.f('ix_stripe_checkout_sessions_status'), table_name='stripe_checkout_sessions')
    op.drop_index('idx_checkout_sessions_user_status', table_name='stripe_checkout_sessions')
    op.drop_table('stripe_checkout_sessions')
    op.drop_index(op.f('ix_stripe_webhook_events_status'), table_name='stripe_webhook_events')
    op.drop_index(op.f('ix_stripe_webhook_events_related_object_id'), table_name='stripe_webhook_events')
    op.drop_index(op.f('ix_stripe_webhook_events_event_type'), table_name='stripe_webhook_events')
    op.drop_index('idx_webhook_events_type_status', table_name='stripe_webhook_events')
    op.drop_index('idx_webhook_events_object', table_name='stripe_webhook_events')
    op.drop_table('stripe_webhook_events')
    # ### end Alembic commands ###
