"""Add user_id to SpeakingExercise

Revision ID: f2d17066fdd5
Revises: 7b587903f1a9
Create Date: 2026-04-29 15:11:06.074197

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f2d17066fdd5'
down_revision: Union[str, None] = '7b587903f1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaking_exercises', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index('idx_speaking_exercises_user_cycle_day', 'speaking_exercises', ['user_id', 'cycle', 'day'], unique=False)
    op.create_foreign_key(None, 'speaking_exercises', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'speaking_exercises', type_='foreignkey')
    op.drop_index('idx_speaking_exercises_user_cycle_day', table_name='speaking_exercises')
    op.drop_column('speaking_exercises', 'user_id')
    # ### end Alembic commands ###
